server:
  servlet:
    context-path: /desafio-starkbank
  port: ${PORT:8080}

spring:
  application:
    name: Desafio Starkbank
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    path: /openapi
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "Desafio TÃ©cnico - Starkbank"
    version: "1.0.0"

starkbank:
  environment: ${STARKBANK_ENV:sandbox}
  project-id: ${STARKBANK_PROJECT_ID}
  private-key: ${STARKBANK_PRIVATE_KEY}
