server:
  servlet:
    context-path: /desafio-starkbank

spring:
  application:
    name: Desafio Starkbank
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    path: /openapi
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "Desafio TÃ©cnico - Starkbank"
    version: "1.0.0"

starkbank:
  environment: sandbox
  project-id: "6044659793002496"
  private-key: |
    -----BEGIN EC PARAMETERS-----
    BgUrgQQACg==
    -----END EC PARAMETERS-----
    -----BEGIN EC PRIVATE KEY-----
    MHQCAQEEIEwaY4ob52Y/lPidbatz+pPnlLp8rKZpt0P1faHgMvJxoAcGBSuBBAAK
    oUQDQgAEGcrNp88o3vZ75mGECvWIHWnYZaGl8nB8i2diCRtQozF95yD1WIFiNDhA
    zh05aTAJHWlIeOTSGYInOQXeZlnfxg==
    -----END EC PRIVATE KEY-----
